name: CI/CD - Brainroom Frontend

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies (optional)
      run: |
        cd frontend
        if [ -f package.json ]; then
          npm install
        else
          echo "No package.json, skipping install"
        fi

    - name: Trigger Netlify Deploy
      run: |
        curl -X POST -d '{}' ${{ secrets.NETLIFY_DEPLOY_HOOK }}
